#! /usr/bin/env python
# -*- coding: utf-8 -*-
import datetime
from ncclient import manager

def net_conf_cisco(DUT_ipaddress):
	m = manager.connect(host=DUT_ipaddress, port=22, username='admin',
                    password='admin', device_params={'name': 'csr'})

	now = datetime.datetime.now()
	try:
		running_config = m.get_config('running')
		log = str(running_config)
		data="C:\\Users\\*****\\Desktop\\python\\netconf\\netconf_cisco\\config_log\\{0:%Y%m%d%H%M%S}_{1}.txt".format(now,DUT_ipaddress)
		with open(data,"a") as f:
			f.write(log)
	except:
		file="C:\\Users\\*****\\Desktop\\python\\netconf\\netconf_cisco\\config_log\\{0:%Y%m%d%H%M}_{1}_SSHError.txt".format(now,DUT_ipaddress)
		with open(file, "a") as f:
			traceback.print_exc(file=f)

file="C:\\Users\\*****\\Desktop\\python\\netconf\\netconf_cisco\\cisco_list.txt"
with open(file,"r") as address_list:
	address = address_list.readlines()
for list in address:
	net_conf_cisco(list.rstrip('\n'))
	#print(list.rstrip('\n'))
